ToolTip support other graphic elements
maptalks/maptalks.js pull request #1017
Opened 2019-10-14 05:19 UTC by deyihu

2019-10-14 07:14 UTC, fuzhenn requested changes

2019-10-14 07:14 UTC, fuzhenn commented on src/ui/ToolTip.js
> +        if (owner instanceof Geometry || owner instanceof UIMarker || (owner && isFunction(owner.on) && isFunction(owner.off))) {
```js
owner instanceof Geometry || owner instanceof UIMarker || 
```
这两个条件可以取消掉了。

2019-10-14 07:17 UTC, fuzhenn commented on src/ui/ToolTip.js
> +        if (owner instanceof Geometry || owner instanceof UIMarker || (owner && isFunction(owner.on) && isFunction(owner.off))) {
判断条件中，应该增加一个是否存在 `owner.getCenter` 方法的判断

我觉得可以考虑在UIComponent上增加一个静态方法`isSupport`，把这几个判断条件挪到这里来实现，这样其他UI组件也能重用。

2019-10-14 07:25 UTC, deyihu commented on src/ui/ToolTip.js
> +        if (owner instanceof Geometry || owner instanceof UIMarker || (owner && isFunction(owner.on) && isFunction(owner.off))) {
getCenter哪里需要使用？，Tooltip和infowindow等位置不是应该有鼠标的位置（e.coordinate）决定的吗？

2019-10-14 07:27 UTC, fuzhenn commented on src/ui/ToolTip.js
> +        if (owner instanceof Geometry || owner instanceof UIMarker || (owner && isFunction(owner.on) && isFunction(owner.off))) {
没有提供位置时，默认用owner的center
https://github.com/maptalks/maptalks.js/blob/master/src/ui/UIComponent.js#L142

2019-11-09 10:51 UTC, fuzhenn approved these changes

2019-11-09 10:51 UTC, merged