add coordinatesToContainerPoints ,Batch conversion for better perform…
maptalks/maptalks.js pull request #1201
Opened 2020-08-26 03:12 UTC by deyihu

…ance fix #1200

2020-08-26 06:36 UTC, fuzhenn requested changes

2020-08-26 06:36 UTC, fuzhenn commented on src/map/Map.js
> +            const t = this._projIfBehindCamera(tempOut, this.cameraPosition, this.cameraForward);
这个方法还是不能提到循环外，tempOut是会参与计算，不同的coordinate值都不同。

2020-08-26 06:38 UTC, fuzhenn commented on src/map/Map.js
> +            const t = this._projIfBehindCamera(tempOut, this.cameraPosition, this.cameraForward);
另外得在MapSpec中增加这个方法的测试。

2020-08-26 07:59 UTC, deyihu commented on src/renderer/geometry/Painter.js
> +            const pts = map._pointsToContainerPoints(viewPoints, glZoom, alts);
我测试了下，性能可以提高一倍

2020-08-29 01:09 UTC, deyihu commented on src/geometry/Path.js
> +        if (!Array.isArray(prjCoords)) {
批量转换

2020-08-29 01:10 UTC, deyihu commented on src/map/Map.Camera.js
> +    _pointsToContainerPoints: function () {
批量转换

2020-08-29 01:10 UTC, deyihu commented on src/map/Map.js
> +    _prjsToPoints(pCoords, zoom) {
批量转换

2020-08-29 01:11 UTC, deyihu commented on src/renderer/geometry/Painter.js
> +        if (mapStateCache && (!this._hitPoint)) {
复用地图状态参数

2020-08-29 01:12 UTC, deyihu commented on src/renderer/layer/vectorlayer/VectorLayerCanvasRenderer.js
> +    _batchConversionMarkers() {
markers 批量转换

2020-08-29 01:12 UTC, deyihu commented on src/renderer/layer/vectorlayer/VectorLayerCanvasRenderer.js
> +                if (isNil(altitudeCache[altitude])) {
复用altitude计算结果

2020-08-29 01:14 UTC, deyihu commented on src/renderer/geometry/symbolizers/PointSymbolizer.js
> +        if (geometry._cPoint && (!ignoreAltitude)) {
直接读取 vectorlayerrender 里的批量转换结果

2020-09-27 02:10 UTC, fuzhenn commented on src/renderer/layer/vectorlayer/VectorLayerCanvasRenderer.js
> +                if (x >= xmin && y >= ymin && x <= xmax && y <= ymax) {
这里可以简单写成
```js
geo._inCurrentView = x >= xmin && y >= ymin && x <= xmax && y <= ymax
```

2020-09-27 02:15 UTC, fuzhenn approved these changes

2020-09-27 03:02 UTC, merged