optimize `this._containerDOM.innerHTML = "''` in `map.remove()`
maptalks/maptalks.js pull request #1208
Opened 2020-08-31 07:39 UTC by rainjay

refer to [issues 1195]( https://github.com/maptalks/maptalks.js/issues/1195)

2020-09-02 07:53 UTC, fuzhenn requested changes

2020-09-02 07:53 UTC, fuzhenn commented on src/map/Map.js
> +            Array.from(this._containerDOM.childNodes)
基本没有问题！
不过maptalks需要兼容到ie9，无法支持Array.from，帮忙做一下对IE9的兼容，谢谢！

2020-09-02 08:36 UTC, rainjay commented on src/map/Map.js
> +            Array.prototype.slice.call(this._containerDOM.childNodes, 0)
已处理，改为  Array.prototype.slice.call(this._containerDOM.childNodes, 0)

2020-09-07 01:56 UTC, fuzhenn approved these changes

2020-09-07 01:56 UTC, merged