reduce function call for optimize marker rendering performance
maptalks/maptalks.js pull request #1306
Opened 2021-01-07 06:50 UTC by deyihu

2021-01-30 09:04 UTC, fuzhenn requested changes

2021-01-30 09:04 UTC, fuzhenn commented on src/renderer/layer/vectorlayer/VectorLayerCanvasRenderer.js
> +                    geo._cPoint = undefined;
应该恢复成 `delete geo._cPoint;`

2021-01-30 09:04 UTC, fuzhenn commented on src/renderer/layer/vectorlayer/VectorLayerCanvasRenderer.js
> +            if (geo._dirtyCoords) {
感觉这里不需要判断dirtyCoords，只需要如下，另一处同理
```js
          if (geo._painter) {
                geo.paint();
            }
```

2021-01-30 09:04 UTC, fuzhenn commented on src/renderer/layer/vectorlayer/VectorLayerCanvasRenderer.js
> +            geo._inCurrentView = undefined;
设置undefined感觉不如 delete 直观

2021-01-30 09:04 UTC, fuzhenn commented on src/renderer/layer/vectorlayer/VectorLayerCanvasRenderer.js
> +                }
这个处理虽能省略getRenderPoints的调用，但假设getRenderPoints中逻辑有变化时，这里会成为潜在的bug点，如果这里对性能影响不大，建议恢复为原有写法。

2021-01-30 09:04 UTC, fuzhenn commented on src/renderer/layer/vectorlayer/VectorLayerCanvasRenderer.js
>                  if (altitudeCache[altitude] == null) {
改为
```js
altitudeCache[altitude] === undefined
```

2021-03-11 01:37 UTC, deyihu commented
减少function call 确实能提高性能，至于代码的优雅性，我在看看

2021-06-11 02:09 UTC, closed without merging