fix marker edit anchors position error  fix #784
maptalks/maptalks.js pull request #1314
Opened 2021-01-19 07:40 UTC by deyihu

2021-01-30 08:33 UTC, fuzhenn requested changes

2021-01-30 08:33 UTC, fuzhenn commented on src/geometry/ext/Geometry.Drag.js
> +    'dragOnAxisOnScreenCoordinates': false
名字改为： `dragOnScreenAxis`

2021-01-30 08:33 UTC, fuzhenn commented on src/geometry/editor/GeometryEditor.js
> +        const shadow = this._shadow;
defaultDxDy的计算逻辑可以简化一下，利用现成的方法：
```js
const markerWidth = symbol['markerWidth'] || 0);
const markerHeight = symbol['markerHeight'] || 0);
let defaultDxDy;
if (Symbolizers.VectorMarkerSymbolizer.test(symbol)) {
  defaultDxDy = Symbolizers.VectorMarkerSymbolizer._getVectorPoints(symbol['markerType'], markerWidth, markerHeight);
} else {
  // getAlignPoint 是strings.js里的方法
  defaultDxDy = getAlignPoint(size , symbol['markerHorizantalAlignment, symbol['markerVerticalAlignment']);
}
```

2021-01-31 09:02 UTC, deyihu commented on src/geometry/editor/GeometryEditor.js
> +        const shadow = this._shadow;
```js

Symbolizers.VectorMarkerSymbolizer._getVectorPoints

``` 

这个方法返回的是锚点吧？是偏移量？

2021-01-31 09:39 UTC, deyihu commented on src/geometry/editor/GeometryEditor.js
> +        const shadow = this._shadow;
我仔细看了下，这个还挺烦的，所有的marker都没有一个声明性文件来说明其horizontalAlignment，verticalAlignment，
我现在只能靠渲染的结果来猜了，就像上次我说的添加一个symbol的说明性文件，来描述所有symbol的默认值

2021-01-31 11:44 UTC, fuzhenn commented on src/geometry/editor/GeometryEditor.js
> +        const shadow = this._shadow;
默认的horizontalAlignment和verticalAlignment都是middle，只是vector marker不同图形，`_getVectorPoints`返回的结果不同。

2021-01-31 14:01 UTC, deyihu commented on src/geometry/editor/GeometryEditor.js
> +        const shadow = this._shadow;
不行，或者我没有看懂，我加了一些方法来解决这个问题

2021-01-31 14:21 UTC, fuzhenn commented on src/renderer/geometry/symbolizers/VectorMarkerSymbolizer.js
>  }
这两个新增方法虽然能解决，但这些逻辑和其他地方有重复，需要做一些重构。
这样吧，我明天调整一下，然后给你的pr提一下pr。

2021-03-10 10:00 UTC, fuzhenn commented
reproduction:
https://codepen.io/deyihu/pen/QWGbpvz?editors=0010

2021-03-11 01:34 UTC, deyihu commented
这个问题需要进一步的讨论，可能需要修改marker锚点的计算方式

2021-06-03 12:04 UTC, deyihu commented
this is fixed by 1.0.0-alpha.17

2021-06-03 12:04 UTC, closed without merging