uimaker support min/max zoom
maptalks/maptalks.js pull request #1323
Opened 2021-01-29 15:14 UTC by deyihu

2021-01-30 06:32 UTC, fuzhenn approved these changes

2021-01-30 06:34 UTC, fuzhenn commented on src/ui/UIComponent.js
> +        if (this.type !== 'uimarker') {
`this.type !== 'uimarker'` 能否替换成 `this.isVisible()`?

2021-01-30 14:00 UTC, deyihu commented on src/ui/UIComponent.js
> +        if (this.type !== 'uimarker') {
我试了下还不行，会影响其他的ui，
https://github.com/maptalks/maptalks.js/blob/fc6e8f24a333e63eb687682316fe31f69a96f6ff/src/ui/UIComponent.js#L173 这个方法会
https://github.com/maptalks/maptalks.js/blob/fc6e8f24a333e63eb687682316fe31f69a96f6ff/src/ui/UIComponent.js#L456 设置didsplay='none'到时 isVisible永远为非，我在UImarker加个其他判断吧

2021-01-30 14:09 UTC, deyihu commented on src/ui/UIComponent.js
> +        if (this.type !== 'uimarker') {
等这个pr合并了，我在处理下一个pr

2021-01-30 14:40 UTC, fuzhenn requested changes

2021-01-30 14:40 UTC, fuzhenn commented on src/ui/UIMarker.js
> +    onZoomEnd() {
这个函数名应该改成onZooming

2021-01-30 14:40 UTC, fuzhenn commented on src/ui/UIMarker.js
> +        // }
删掉这些注释

2021-01-30 14:40 UTC, fuzhenn commented on src/ui/UIMarker.js
> +        }
这一段可以简写为:
```js
if (!this.getMap() || !this.getDOM()) {
  return;
}
```

2021-01-30 15:48 UTC, deyihu commented on src/ui/UIMarker.js
> +    onZoomEnd() {
这个名字还不能乱改，这是重写UIComponent
里面还包含了其他的事件的处理逻辑 
https://github.com/maptalks/maptalks.js/blob/fc6e8f24a333e63eb687682316fe31f69a96f6ff/src/ui/UIComponent.js#L546

否则就要动 UIComponent里的逻辑了

2021-01-30 15:54 UTC, fuzhenn commented on src/ui/UIMarker.js
> +    onZoomEnd() {
的确，onEvent和onZoomEnd都是父类里定义了的方法
但应该可以不改onEvent和onZoomEnd，就能实现你想要的功能。
onZooming调用的是updatePosition，里面有帧同步机制，直接setPosition会导致缩放过程中图形不同步。

2021-01-31 06:52 UTC, fuzhenn approved these changes

2021-01-31 06:52 UTC, merged