In drawing mode, do not trigger geometry events by config map geometr…
maptalks/maptalks.js pull request #1379
Opened 2021-06-24 04:57 UTC by deyihu

close maptalks/maptalks.js#1337

2021-06-25 09:12 UTC, deyihu commented
fix #1337 
fix #1380

2021-06-28 11:16 UTC, fuzhenn requested changes

2021-06-28 11:16 UTC, fuzhenn commented on src/map/Map.js
> +    isDrawing() {
这里还是不宜给map增加新的方法和状态。
可以改为在DrawTool的options中增加geometryEvents选项，如果设为false，就设置map状态:
```js
this._geometryEvents = map.options['geometryEvents'];
map.config('geometryEvents', false);
```
drawTool.disable时恢复。
```js
map.config('geometryEvents', this._geometryEvents);
```

2021-07-05 02:38 UTC, fuzhenn approved these changes

2021-07-05 02:38 UTC, merged