Optimize the pick performance of polygon and linestring
maptalks/maptalks.js pull request #1539
Opened 2021-12-13 08:19 UTC by deyihu

2021-12-22 13:37 UTC, fuzhenn requested changes

2021-12-22 13:37 UTC, fuzhenn commented on src/geometry/Geometry.js
> +    _isPoly() {
我觉得可以删除 `_isPoly` 方法，在Geometry上增加 `_isStrokeFill` 方法。
`_isStrokeFill` 方法返回的值就是下面的 `isOnlyStrokeAndFillSymbol`。
方法的实现宜用重载来实现。
Geometry上的值永远返回false
改在Path类和MultiPath类上来实现 `isStrokeFill` 的真正逻辑

2021-12-22 13:37 UTC, fuzhenn commented on src/geometry/Geometry.js
> +        if (isInMapView && isPoly && isOnlyStrokeAndFillSymbol && painter._containerBbox) {
在原有的containsPoint增加参数不是一个好的设计。
可以把isInMapView的相关逻辑单独提成一个方法，例如叫 `_isInsideContainerExtent`
在下面的循环中根据 isInMapView 来决定调用 `_isInsideContainerExtent` 还是 `_containsPoint`

2021-12-22 13:37 UTC, fuzhenn commented on src/geometry/GeometryCollection.js
> +    _containsPoint(point, t, isInMapView) {
这里同理，增加一个 `_isInsideContainerExtent`  方法，去掉这里的 isInMapView 参数

2021-12-23 05:41 UTC, deyihu commented on src/geometry/Geometry.js
> +    _isPoly() {
_isStrokeFill 不应该是geometry的方法，应该是 painter的方法，所有这个方法就放在geometry不太好

2021-12-23 05:45 UTC, deyihu commented on src/geometry/Geometry.js
> +    _isPoly() {
_isPoly 还不能去掉，仅仅isOnlyStrokeAndFillSymbol 还不能区分 linestring,arccurve 等推行

2022-08-15 09:27 UTC, closed without merging