Rollback to loadTileImage when user custom tilelayer loadTileImage fi…
maptalks/maptalks.js pull request #1581
Opened 2022-02-08 14:43 UTC by deyihu

…x #1580

2022-02-09 01:08 UTC, fuzhenn requested changes

2022-02-09 01:08 UTC, fuzhenn commented on src/layer/tile/TileLayer.js
> +        const url = msg.data.url;
worker代码里不能用const或let等es6语法，ie11不支持。

2022-02-09 01:10 UTC, deyihu commented on src/layer/tile/TileLayer.js
> +        const url = msg.data.url;
不会的，babel会转译的，这个不是字符串，是函数，babel会转译的

2022-02-09 01:13 UTC, fuzhenn commented on src/renderer/layer/tilelayer/TileLayerCanvasRenderer.js
> +    checkUrl(url) {
这个checkUrl是用来干嘛的？

2022-02-09 01:20 UTC, deyihu commented on src/renderer/layer/tilelayer/TileLayerCanvasRenderer.js
> +    checkUrl(url) {
对url进行容错处理，比如url是相对协议

2022-02-11 03:07 UTC, fuzhenn requested changes

2022-02-11 03:07 UTC, fuzhenn commented on src/renderer/layer/tilelayer/TileLayerCanvasRenderer.js
> +        const protocol = url.substring(0, 2).toLocaleLowerCase();
感觉这个判定还不够强。应该找个判断是否是绝对路径的regex来判定url是否是绝对路径。
如果是相对路径，就调用 util.js 中的getAbsoluteURL方法来转成绝对路径。

2022-02-25 08:47 UTC, fuzhenn approved these changes

2022-02-25 08:47 UTC, merged