worker code support Asynchronous injection
maptalks/maptalks.js pull request #2016
Opened 2023-07-12 07:02 UTC by deyihu

fix #2015

2023-07-14 09:12 UTC, deyihu commented on src/core/Eventable.js
> +                            if (!Browser.isTest) {
方便测试而已，测试环境开了，就不用log,可以让ci跑的更快和输出更加干净

2023-07-14 09:13 UTC, deyihu commented on src/core/worker/Worker.js
> +export function createAdapter(key, cb) {
利用worker把用户动态注入的code发送到worker里，然后再worker里动态生成adapter,并挂到adpters上

2023-07-14 09:14 UTC, deyihu commented on src/core/worker/Worker.js
> +        if (msg.messageType === 'createAdapter') {
如果是动态注入worker

2023-07-14 09:15 UTC, deyihu commented on src/core/worker/Actor.js
> +        this._delayMessages = [];
延迟消息，如果一个worker是动态创建的，在这个过程中，用户可能发送消息

2023-07-14 09:15 UTC, deyihu commented on src/core/worker/Actor.js
> +        this._delayMessages.forEach(message => {
处理延迟消息

2023-07-14 09:16 UTC, deyihu commented on src/core/worker/Actor.js
> +        if (this.initializing) {
当worker动态创建时，拦截消息，并加入到延迟消息队列，等worker创建完成了，在发送到worker里

2023-07-21 09:15 UTC, deyihu commented on src/core/worker/Worker.js
> +    const workers = workerPool.workers || [];
必须是所有的worker，即每个worker里都要注入改adapter

2023-07-25 04:00 UTC, fuzhenn requested changes

2023-07-25 04:00 UTC, fuzhenn commented on src/core/worker/Actor.js
> +            console.log(`Dynamic Create Adapter for worker:${workerKey}`);
改成 `Injecting codes in worker with worker key: :${workerKey}`
另外worker中的adapter存在三种状态： 没有初始化，正在初始化，完成初始化
这里只判断了没有初始化，还应该增加正在初始化的逻辑

2023-07-25 08:54 UTC, merged