UIMarker Can only be added to the map
maptalks/maptalks.js pull request #2162
Opened 2023-12-21 02:27 UTC by deyihu

fix #2161

2023-12-21 03:07 UTC, fuzhenn requested changes

2023-12-21 03:07 UTC, fuzhenn commented on src/layer/OverlayLayer.js
> +                    console.warn(geometries[i], 'is not Geometry,This may not be a correct operation');
我觉得可以不用warn，直接报错。
提示文本可以改成 ' is not a valid Geometry adding to layer(' + id + ').');

2023-12-21 03:07 UTC, fuzhenn commented on src/layer/OverlayLayer.js
> +            console.warn('geometries is empty');
这里不用warn

2023-12-21 03:07 UTC, fuzhenn commented on src/layer/OverlayLayer.js
> +            if (geo.isUI) {
```instanceof Geometry``` 应该就足够了，不需要再增加isUI判断，不是Geometry的就都throw Error报错，类似ts里声明了类型的数组，是不能放置别的类型的数据的。

2023-12-22 08:41 UTC, fuzhenn requested changes

2023-12-22 08:41 UTC, fuzhenn commented on src/geometry/Geometry.js
> +        this.isGeometry = true;
isGeometry和下面的isUI，isLayer都没有用到，应该删除掉

2023-12-22 08:42 UTC, fuzhenn requested changes

2023-12-22 08:42 UTC, fuzhenn commented on src/layer/OverlayLayer.js
> +                console.error(geo, 'is null');
提示也应该写成：
console.error(geo, ' is not invalid geometry to add to layer(' + this.getId() + ') at index:' + i);

2023-12-22 09:46 UTC, deyihu commented on src/geometry/Geometry.js
> +        this.isGeometry = true;
故意加的，方便后续快速判断一个对象是图层，是图形，还是hi

2023-12-25 07:16 UTC, fuzhenn commented on src/geometry/Geometry.js
> +        this.isGeometry = true;
这个设计不是很好，感觉更应该用 instanceof 来判断

2024-01-05 07:41 UTC, fuzhenn approved these changes

2024-01-05 07:41 UTC, merged