Optimize idle scheduling
maptalks/maptalks.js pull request #2349
Opened 2024-06-07 08:40 UTC by deyihu

2024-06-13 09:25 UTC, fuzhenn requested changes

2024-06-13 09:25 UTC, fuzhenn commented on src/core/MicroTask.ts
>      if (Browser.requestIdleCallback && idleEnable) {
感觉idleFrameLoop中可以不用做那些复杂判断，只需要执行loop并记录idleCallTime：
因为idleFrameLoop能执行，说明idleEnable和reuqestIdleCallback肯定都是生效的，而且无论deadline情况如何，都可以执行loop，所以相关的判断可以去掉

2024-06-13 09:25 UTC, fuzhenn commented on src/core/MicroTask.ts
> +        requestIdleCallback(idleFrameLoop, { timeout: idleTimeout });
可以去掉requestIdleCallback里的timeout设置，因为animFrameLoop中已经实现了idle是否超时的判断逻辑

2024-06-13 09:35 UTC, deyihu commented on src/core/MicroTask.ts
> +        requestIdleCallback(idleFrameLoop, { timeout: idleTimeout });
timeout 还是要要的，开启调试模式时，希望用户能清楚明白的知道idle超时了

2024-06-13 09:44 UTC, fuzhenn commented on src/core/MicroTask.ts
> +        requestIdleCallback(idleFrameLoop, { timeout: idleTimeout });
是的，用户确实可以通过timeout了解到主线程比较忙，idleCallback申请不到。
如果忽略timeout，那idleFrameLoop可以变成：
```js
function idleFrameLoop() {
    loop();
    idleCallTime = now();
}
```
因为目前的实现下，idle是否busy已经不再影响loop的执行，所以用户知道或者不知道idle busy已经没那么重要。
相比之下，我觉得去掉timeout，更简单的idleFrameLoop代码的收益是更大。

如果觉得idle busy的调试信息非常重要，必须要明确告知用户，也可以在animFrameLoop中增加计数，超时执行的loop次数超过某个次数（比如10次），就warn一下，也能达到同样的效果，实现也更简洁。

2024-06-19 02:38 UTC, fuzhenn commented
关于调用requestIdleCallback是否设置timeout参数，去掉timeout的pros和cons分析如下：

### pros
* GlobalConfig里的idleEnable，idleTimeRemaining和idleTimeout设置都不再需要，可以取消掉。
* 更简单的idleFrameLoop代码实现：
```js
function idleFrameLoop() {
    loop();
    idleCallTime = now();
    requestIdleCallback(idleFrameLoop);
}
```

### cons
* 用户无法通过timeout知道idle是否busy，但因为目前的实现下，idle是否busy已经不再影响loop的执行，所以用户知道或者不知道idle busy已经没那么重要。如果觉得idle busy的调试信息非常重要，必须要明确告知用户，也可以在animFrameLoop中增加计数，超时执行的loop次数超过某个次数（比如10次），就warn一下，也能达到同样的效果，实现也更简洁。

综上，我个人觉得应该在调用requestIdleCallback时去掉timeout参数

2024-06-19 03:05 UTC, deyihu commented
idleTimeRemaining 还是要需要的，注意这个idle主要用来worker通信，不判断idleTimeRemaining的话，那主线程渲染又卡了，设么意思？比如现在idleTimeRemaining是1，那就意味着worker通信可以了，但是这时主线程可能正在渲染，然后就有回到解放前了

2024-06-21 02:52 UTC, fuzhenn commented
> idleTimeRemaining 还是要需要的，注意这个idle主要用来worker通信，不判断idleTimeRemaining的话，那主线程渲染又卡了，设么意思？比如现在idleTimeRemaining是1，那就意味着worker通信可以了，但是这时主线程可能正在渲染，然后就有回到解放前了

我感觉这个判断还是复杂了，我觉得idleFrameLoop里可以不用管deadline的timeRemaining情况，只要idleFrameLoop被调用就执行loop。

现在animFrameLoop中已经设定，如果超过threshold就执行loop，所以不用担心线程忙，idleCallback迟迟不执行的情况。（不过目前threshold默认的100有点太大，我觉得可以适当减少，比如减少为48（即三帧以内idleFrameLoop不执行则直接在animFrameLoop中执行loop）。）

分几种情况来分析：
* 主线程一直很忙，idleFrameLoop一直无法执行，在animFrameLoop中每隔三帧就执行一次
* 主线程不忙，idleFameLoop则一直能申请到，loop会一直在idleFrameLoop中执行，不会在animeFrameLoop中执行。
* 主线程有突发性业务，在一段时间内很忙，则在忙的期间在animeFrameLoop中执行loop，不忙以后在idleFrameLoop中执行

这样，忙的时候loop也不会被显著延迟（每三帧执行一次），闲的时候也能利用到idleFrameLoop来执行loop逻辑，最终代码的形式大概如下：

```js
let idleCallTime = now();
function idleFrameLoop() {
   loop();
   idleCallTime = now();
    requestIdleCallback(idleFrameLoop);
}

function animFrameLoop() {
    if (Browser.requestIdleCallback) {
        const { idleForceTimeThreshold, idleLog } = GlobalConfig;
        const time = now();
        // threshold缩小到48
        if (time - idleCallTime > idleForceTimeThreshold) {
            loop();
            idleCallTime = now();
            if (idleLog) {
                console.warn(`did not apply for availability, forced run idle`);
            }
        }
    } else {
        loop();
    }
    requestAnimFrame(animFrameLoop);
}
```

2024-06-21 03:19 UTC, merged