fix Geometry miss rotate info when toJSON
maptalks/maptalks.js pull request #2378
Opened 2024-07-08 02:32 UTC by deyihu

fix #1625

2024-07-08 02:54 UTC, fuzhenn commented
感觉有些问题，因为rotate方法会改变geometry的coordinates，toJSON记录下来的是rotate之后的coordinates，在这个coordinates基础上是不需要再rotate的

2024-07-08 04:04 UTC, deyihu commented
刚更新了下，当且仅当不是坐标串的图形记录，注意记录的是旋转点的坐标，即fromJSON时还是原来旋转前的坐标作为参考中心，所以旋转后的坐标还是json里保存的坐标，举例：假设一个矩形的坐标是[0,0],按照旋转中心旋转后结果是[1,],反序列化时，还是哪的[0,0]坐标旋转点来处理的，处理的结果仍然是[1,1]

2024-07-15 02:43 UTC, fuzhenn commented
感觉还有以下三个问题没解决：
* pivot不为null时，coordinates仍然会改变
* 多次调用rotate时，只会记录最后一次的rotateAngle，前面的rotateAngle都会丢失
* 测试缺少rotate方法存在pivot参数时的用例

2024-07-15 02:44 UTC, fuzhenn requested changes

2024-07-15 02:44 UTC, fuzhenn commented on test/geometry/GeometrySpec.js
> +                expect(json.options.rotateAngle).to.eql(angle);
这里需要对geo的坐标值也做一下判断

2024-07-15 03:10 UTC, deyihu commented on src/geometry/Geometry.ts
> +            if (this.getShell) {
Ellipse等图形才会记录这些旋转信息

2024-07-15 03:17 UTC, deyihu commented on test/geometry/GeometrySpec.js
> +                expect(json.options.rotateAngle).to.eql(angle);
1. 关于旋转的信息，只有Ellipse,Rectangle等图形才会记录，Marker,LineString这些并不会记录，用的就是修改后的坐标
2.  Ellispe这些图形，旋转时并不会改变坐标 https://github.com/maptalks/maptalks.js/blob/d8e5928a03c0cd48c4d12f0ab34aa442315743d5/src/geometry/Geometry.ts#L1160  ，不管进行多少次旋转，只会记录最后一次旋转信息，注意即使改变选中中心点也不会改变其坐标的，其坐标是动态的在投影坐标里计算的  https://github.com/maptalks/maptalks.js/blob/d8e5928a03c0cd48c4d12f0ab34aa442315743d5/src/geometry/Geometry.ts#L1172   
3. 因为旋转时并不会改变坐标，所以没有必要测试坐标的改变

2024-08-08 03:44 UTC, fuzhenn commented on src/geometry/Geometry.ts
> +            if (this.getShell) {
但感觉也会影响到Polygon？

2024-08-08 05:40 UTC, deyihu commented on src/geometry/Geometry.ts
> +            if (this.getShell) {
不会，因为代码里已经做了判断了,只有坐标非数组的情况下才会走这个逻辑

```js

  if (!Array.isArray(coordinates)) {
            //exclude Rectangle ,Ellipse,Sector by shell judge
            if ((pivot.x !== coordinates.x || pivot.y !== coordinates.y) && !this.getShell) {
                const c = measurer._rotate(coordinates, pivot, angle);
                this.setCoordinates(c);
            } else {
                //only redraw ,not to change coordinate
                this.onPositionChanged();
            }
            if (this.getShell) {
                this.options.rotateAngle = angle;
                this.options.rotatePivot = pivot.toArray();
            }
            return this;
        }
        forEachCoord(coordinates, c => {
            return measurer._rotate(c, pivot, angle);
        });
        this.setCoordinates(coordinates);
        return this;

```

2024-08-08 07:42 UTC, merged