当使用自定义切片服务时，超出地图范围则请求缺省图片
maptalks/maptalks.js pull request #778
Opened 2018-09-12 08:44 UTC by davidweining2333

当使用自定义切片服务时，超出地图范围则请求缺省图片[https://github.com/maptalks/maptalks.js/issues/768](url)

2018-09-12 09:40 UTC, davidweining2333 commented
@fuzhenn 老哥，这没事单测没过吗，我给getTileUrl加了一个形参，需要如何改一下单测吗

2018-09-12 11:58 UTC, fuzhenn commented
感谢提PR！ 这个功能很有用，不过有些API应该有更好的设计
明天我找个时间来看一下
再次感谢

对了，emptyUrl不要用写死的maptiler.com上的文件，应从options里读取设置，比如this.options['emptyUrl']之类

2018-09-13 01:48 UTC, davidweining2333 commented
@fuzhenn 嗯对的，这里我想的是如果用户不指定的话应该有缺省值，这个emptyImg是我从openlaysers的一个demo里看的，我后来想了下使用第三方的url可靠性确实不高。而且我自己测试的时候发现使用这个地址的图片请求会受同源策略影响，服务器没配置跨域策略的话，应该是默认crossOrigin影响的，我试过去掉代码里添加的crossOrigin属性，可以请求这个图片，但是在对地图进行pitch的时候会报错程序导致阻塞

2018-09-16 01:59 UTC, fuzhenn commented
Hi， @davidweining2333 
很抱歉拖了几天才回复：
* `getTileUrl`中的逻辑可以去掉
* 这里的res应该改回true
  https://github.com/maptalks/maptalks.js/pull/778/files#diff-3f49a8ff6a11ba84077e52012d41910bR93
* `isOutOfExtent` 可以简写成 `out`
等你这边修改合并后，我会增加一下out瓦片的处理逻辑，顺带把 #778 修改掉

2018-09-16 02:00 UTC, fuzhenn requested changes

2018-09-16 02:00 UTC, fuzhenn commented on src/layer/tile/TileLayer.js
> +    getTileUrl(x, y, z, isOut) {
去掉这里的逻辑

2018-09-16 02:00 UTC, fuzhenn commented on src/layer/tile/tileinfo/TileConfig.js
> +        return this.getNeighorTileIndex(tileIndex['x'], tileIndex['y'], 0, 0, res);
改回true

2018-09-16 02:00 UTC, fuzhenn commented on src/layer/tile/tileinfo/TileConfig.js
> +            isOutOfExtent
isOutOfExtent可以简写为out即可

2018-09-17 03:42 UTC, fuzhenn requested changes

2018-09-17 03:42 UTC, fuzhenn commented on src/layer/tile/tileinfo/TileConfig.js
>              const ext = this._getTileFullIndex(res);
可以把这一行提到isRepeatWorld之前，下面就不用判断`typeof res === 'object'`了

2018-09-17 03:59 UTC, davidweining2333 commented on src/layer/tile/tileinfo/TileConfig.js
>              const ext = this._getTileFullIndex(res);
![image](https://user-images.githubusercontent.com/28379395/45605603-b3c5fa80-ba70-11e8-843b-d763e60a1a43.png)

我之前就是提出来的，可是会有问题，截图1里有对这个函数的调用，就是有这个问题我把true改成res，如果改回true传给_getTileFullIndex，会报错的

2018-09-17 05:17 UTC, fuzhenn commented on src/layer/tile/tileinfo/TileConfig.js
>              const ext = this._getTileFullIndex(res);
啊，确实，那里的true应该改成res，看来这里还是个陈年bug，只是因为调用的巧合，不会走到错误的逻辑里。

感谢感谢，哈哈

2018-09-17 05:42 UTC, davidweining2333 commented on src/layer/tile/tileinfo/TileConfig.js
>              const ext = this._getTileFullIndex(res);
好的，那我重新改一下

2018-09-17 12:17 UTC, fuzhenn approved these changes

2018-09-17 12:23 UTC, merged

2018-11-22 06:30 UTC, davidweining2333 commented
@fuzhenn 老哥，这个out的的逻辑是不是还没添加呀

2018-11-22 07:47 UTC, fuzhenn commented
喔，对，我给忘了 😳

2018-11-23 01:57 UTC, davidweining2333 commented
@fuzhenn 确实关了这个issue没得跟踪了会忘得哈哈，看你有空的时候写一下吧

2018-11-23 03:16 UTC, fuzhenn commented
可不是~
添加了 issue #825