add containerClass to the option of scalcontrl
maptalks/maptalks.js pull request #787
Opened 2018-09-18 07:33 UTC by Liquid-Zhangliquan

user can set containerClass for the scalControl's container

2018-09-18 11:58 UTC, fuzhenn requested changes

2018-09-18 11:58 UTC, fuzhenn commented on src/control/Control.Scale.js
> +    'containerClass': 'maptalks-scalcontrol'
默认改为null

2018-09-18 11:58 UTC, fuzhenn commented on src/control/Control.Scale.js
> +        if (this.options['metric'] && this.options['containerClass']) {
可以简单写成
```js
if (this.options['metric']) {
  this._mScale = createElOn('div', this.options['containerClass'] ? null : css, this._scaleContainer);
}
```
下面的逻辑同理

2018-09-18 12:01 UTC, Liquid-Zhangliquan commented on src/control/Control.Scale.js
> +        if (this.options['metric'] && this.options['containerClass']) {
ok 我改好后再提交

2018-09-18 12:18 UTC, fuzhenn requested changes

2018-09-18 12:18 UTC, fuzhenn commented on src/control/Control.Scale.js
> + *     containerClass :'null'
null,不是'null'

2018-09-18 12:18 UTC, fuzhenn commented on src/control/Control.Scale.js
> +        if (this.options['imperial'] && this.options['containerClass']) {
判断条件里的判断应该删掉
```js
&& this.options['containerClass']
```

2018-09-18 12:53 UTC, fuzhenn requested changes

2018-09-18 12:53 UTC, fuzhenn commented on src/control/Control.Scale.js
> + * @property {String|Object} [options.containerClass=maptalks-scalcontrol]           - scalControl's container div's CSS class
[options.containerClass=maptalks-scalcontrol]改成[options.containerClass=null]

2018-09-18 12:53 UTC, fuzhenn commented on src/control/Control.Scale.js
> + *     containerClass :null
: 后面增加一个空格

2018-09-18 12:53 UTC, fuzhenn commented on src/control/Control.Scale.js
> +        this._scaleContainer = createEl('div', this.options['containerClass'] ? this.options['containerClass'] : null);
这里只需要用 this.options['containerClass'] 即可

2018-09-18 12:53 UTC, fuzhenn commented on test/map/control/Control.ScaleSpec.js
> +            containerClass:null
null前面加个空格

2018-09-18 12:53 UTC, fuzhenn commented on test/map/control/Control.ScaleSpec.js
>          map.addControl(control);
应该新增一个测试用例，设置containerClass，然后判断一下dom的class是否正常设置

2018-09-19 09:42 UTC, fuzhenn requested changes

2018-09-19 09:42 UTC, fuzhenn commented on test/map/control/Control.ScaleSpec.js
> +        var control1 = new maptalks.control.Scale({
应该创建一个新的测试用例
它的用例不是判断innerHTML是否是空，而是control.getDOM()的className是不是`myContainerClass`

2018-09-20 03:23 UTC, closed without merging