Issue876  https://github.com/maptalks/maptalks.js/issues/876
maptalks/maptalks.js pull request #877
Opened 2019-03-11 07:26 UTC by deyihu

example  https://codepen.io/deyihu/pen/BbdZxB?editors=0110

2019-03-11 13:11 UTC, fuzhenn commented
实现本身完全没问题，不过我觉得改为handler来实现会更合理。

给map增加一个默认关闭的 `autoPanAtEdge` handler，然后在drawTool的onEnable方法里，默认把这个handler打开，然后在onDisable里关闭。

这样drawTool里的修改更少， autoPanAtEdge 也能重用

2019-03-11 15:22 UTC, deyihu commented
好的，我更新一下

2019-03-12 04:36 UTC, fuzhenn requested changes

2019-03-12 04:36 UTC, fuzhenn commented on src/map/tool/DrawTool.js
> +            map.config({ autoPanAtEdge: false });
这里需要检查drawtool enable之前，map原有的autoPanAtEdge是否是true，如果是，则这里不应关闭autoPanAtEdge

2019-03-12 07:44 UTC, merged